### PR TITLE
Footer Updated

### PR DESCRIPTION
**Pull request by Devenkapoor7303**
Added Four columns and removed the dotted lines from columns and removed contact with us 

Capture

### CODE REVIEW

**Comment by luckykumarirai** [comment]
@Devenkapoor7303  Solve conflicts then I will merge.

**Comment by Devenkapoor7303** [comment]
Okay

**Comment by Devenkapoor7303** [comment]
@luckykumarirai Can u please tell me how should i resolve these conflicts  becoz i don't know how to resolve the conflicts

**Comment by luckykumarirai** [comment]
@Devenkapoor7303 Join discord for further discussion on that and I will explain how to solve conflicts.

**Comment by Devenkapoor7303** [comment]
Okay

**Pull request closed without merging**
