### PR TITLE
added a single command to run server with client together

### PR DESCRIPTION
**Pull request by Devenkapoor7303**
The server is running at port 5000 and react app is also working with it with a single command 
npm run dev
but i have made some changes in the directory I have put ur react app in client directory and server is present outside the client directory.
Capture

### CODE REVIEW

**Review by luckykumarirai — CHANGES_REQUESTED** [review]
@Devenkapoor7303 No need to change the structure of the directory. You can do without that also.

**Comment by Devenkapoor7303** [comment]
Okay I will do it

**Comment by luckykumarirai** [comment]
@Devenkapoor7303 Before making PR you should make a branch with the relevant name of your work.

**Comment by Devenkapoor7303** [comment]
okay i will add a branch

**Pull request closed without merging**
